Fix apply worker crash when delete-delete conflict occurs (#107)
* Fix apply worker crash when delete-delete conflict occurs

When two nodes in BDR group deleted the same tuple, delete-delete
conflict occurs, the upstream node will not find the target tuple.
When trying to resolve the conflict, the apply worker fails with:

ERROR: trying to store a heap tuple into wrong type of slot
CONTEXT: apply DELETE from remote relation public.city in ...
LOG: background worker "bdr apply worker" (PID 626109) ...

Reason for this crash is that, for heap AM, table_slot_create
returns a slot of type TTSOpsBufferHeapTuple, see
heapam_slot_callbacks(). When tuple to be deleted is not found,
the target slot (oldslot) type will remain TTSOpsBufferHeapTuple.
Since the target slot is not guaranteed to be TTSOpsHeapTuple type
slot here, hence, we use ExecForceStoreHeapTuple().

A tap test generating delete/delete conflict is added which fails
without the fix.

This happens only with PG versions >= 12, that's when
table_slot_create() was introduced, see upstream Postgres commit
4da597edf1bae0cf0453b5ed6fc4347b6334dfe1.

* Add a check for the expected delete-delete conflict

After the conflict is logged, just check for the expected
delete-delete output.

Per review comment.

* Fix a typo in test

---------

Co-authored-by: Bharath Rupireddy <bharath.rupireddyforpostgres@gmail.com>