Assorted code improvements (#84)
* Assorted code improvements

This commit does the following:
- Removes unnecessary newline characters at the end of error
  message in elog/ereport.

- Rewords postgres version specific commit related comments to
  specify what exactly the upstream postgres commit does.

- Removes unnecessary FreeFile/LWLockRelease/CloseTransientFile
  calls before an error. Because, the open file descriptors are
  closed on error via
  BeforeShmemExit_Files->CleanupTempFiles->FreeDesc, and locks
  are released on error via ProcKill->LWLockReleaseAll.

- Combines multiple appendStringInfo calls to single call to
  prepare remote query/conninfo.

- Moves LSN_FORMAT_ARGS from compat/11 to bdr.h to avoid
  duplicating it under compat/{12,13} as it is introduced in
  upstream postgres 14.

- Rewords error messages containing bdr.bdr_nodes.status to be
  more clear.

* Address review comments

- Retain LWLockRelease() before error. A comment in ProcKill()
  around LWLockRelaseAll() says it expects the locks to be
  cleaned-up. While it's no harm to let ProcKill clean up the
  locks held by the backend/process, the real harm if done so is
  this: if any of BDR's on_exit callbacks getting called before
  ProcKill ()->LWLockReleaseAll() that require the same lock comes
  around, they get stuck in LWLockAcquire().

- Replace ("....%d, %d", 1, 1); with ("...1, 1");.

* Release correct lock in bdr_locks.c

Previous commit added, LWLockRelease(BdrWorkerCtl->lock); in
bdr_locks.c instead of LWLockRelease(bdr_locks_ctl->lock); causing
ERROR:  lock bdr_shmem is not held.

A miss-out from previous commit.

---------

Co-authored-by: Bharath Rupireddy <bharath.rupireddyforpostgres@gmail.com>