Emit better error message when pgactive is not setup yet (#220)
When the database isn't joined to pgactive (right after just
creating pgactive extension), if some of the pgactive functions
that look for pgactive node identifier are called, they all will
error out with

ERROR:  function
pgactive._pgactive_node_identifier_getter_private() does not exist

This node identifier getter function is private to pgactive, hence
emit a better message in these cases.