Add error reporting facility when logical join fails during initial sync
This commit adds support to report the last error that occurred
during logical join initial sync phase i.e. during dump and
restore from the upstream node. The error message is stored in
pgactive shared memory which is exposed via a new function. The
pgactive_wait_for_node_ready then looks for the error message, and
errors out with something like the below giving user a more
detailed info than just waiting forever:

NOTICE:  restoring database 'postgres', 100% of 8139 kB complete
ERROR:  previous init of node foo failed with error message: process XXX to execute command "/path_to/pg_restore" for init_replica exited with exit code 1
HINT:  Check server logs for more details.
CONTEXT:  PL/pgSQL function pgactive.pgactive_wait_for_node_ready(integer,integer) line 60 at RAISE