Fix sporadic failure in 045_unregister_workers_after_part.pl (#97)
Sporadically a test case in 045_unregister_workers_after_part.pl
fails as follows:

not ok 19 - unregistering apply worker on node_0 is detected

ERROR:  this BDR node might still be active, not removing
bdr.remove_bdr_from_local_node(boolean,boolean) line 28 at RAISE'

Issue and fix is similar to a recent commit 0c19cc799ea7.

Co-authored-by: Bharath Rupireddy <bharath.rupireddyforpostgres@gmail.com>