Fix flakiness in TAP tests (#165)
Two of the TAP tests in 045_unregister_workers_after_detach.pl
and 120_bdr_remove_bdr_from_node.pl are failing sporadically as
following:

not ok 19 - unregistering apply worker on node_0 is detected
ERROR:  this BDR node might still be active, not removing

These failures seem to be due to the function
check_detach_status() in TAP tests not checking the local node
status to be 'k'/killed. IOW, check_detach_status() doesn't check
if node_status of a detached node in bdr.bdr_nodes table is 'k'.
While this works for other callsites of check_detach_status(), the
two sporadically failing TAP tests need to the detached node to
know it is actually detached. In
045_unregister_workers_after_detach.pl, the apply worker
unregisters only upon detecting the node_status is 'k'. In,
120_bdr_remove_bdr_from_node.pl, the non-force bdr.bdr_remove(),
raises exception when the node_status is not 'k'.

Fix provided in this commit ensures the node_status on detached
node is 'k' before the check for unregistering apply worker and
non-force bdr.bdr_remove().

While here, two other improvements are done:
- Removed a duplicate export of check_detach_status() in
t/utils/nodemanagement.pm

- Used 2 node BDR group in 045_unregister_workers_after_detach.pl,
the 3rd node wasn't actually used for any purpose. This saves an
unnecessary node bringup time.

Co-authored-by: Bharath Rupireddy <bharath.rupireddyforpostgres@gmail.com>