fix delete on pg_depend in remove_bdr_from_local_node()
Too many entries were deleted in pg_depend leading to:

=# select bdr.remove_bdr_from_local_node();
NOTICE:  removing BDR from node
INFO:  BDR 1.0 global sequences not supported, nothing to convert
NOTICE:  BDR removed from this node. You can now DROP EXTENSION bdr and, if this is the last BDR node on this PostgreSQL instance, remove bdr from shared_preload_libraries.
 remove_bdr_from_local_node
----------------------------

(1 row)

=# drop table foo;
DROP TABLE

=# create table foo (a int primary key);
ERROR:  type "foo" already exists
HINT:  A relation has an associated type of the same name, so you must use a name that doesn't conflict with any existing type.

Note that dropping the relation before calling remove_bdr_from_local_node() does
not produce the issue.

Updating 120_bdr_remove_bdr_from_node.pl to test the failing scenario (it would
fail with the same error without the patch).

Without this fix a re-join would fail too (the table being re-created during the
pg_restore stage).