Release correct lock in bdr_locks.c
Previous commit added, LWLockRelease(BdrWorkerCtl->lock); in
bdr_locks.c instead of LWLockRelease(bdr_locks_ctl->lock); causing
ERROR:  lock bdr_shmem is not held.

A miss-out from previous commit.